// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbgpyxktjowhcixpsbzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiZ3B5eGt0am93aGNpeHBzYnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3NzM5OTcsImV4cCI6MjA1MDM0OTk5N30.6NOI1u8EZkQOBIhO7aw3wEsX_fzp9fbbgqO_JdgHKjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);